## This content is duplicated here from configs/config_designers.yml because I'm building this site through Github Pages, and Github Pages just looks for the _config.yml file in the root directory to create the build.
# project definitions
project: doc_designers
audience: designers
product: all
platform: all
version: all
destination: ../doc_designers
topnav_title: Documentation
homepage_title: Frontdesk Anywhere Documentation 
site_title: Frontdesk Anywhere Documentation 
# disqus_shortname: idrbwjekyll
google_analytics: 
github_editme_path: fdazen/fda-documentation
baseurl: /build
url: http://docs.frontdeskanywhere.net
# don't use a slash before or after the above path. here's how this url gets written out in page.html: https://github.com/{{site.github_editme_path}}{{page.url | replace: '.html', '.md'}}
# variables

sidebar_tagline: Documents
sidebar_version: version 3.2.34.2

port: 4001

exclude:
  - doc_writers*
  - configs/
  - _site
  - doc_multi*

# same for all
host: 127.0.0.1
feedback_email: help@frontdeskanywhere.com
sidebar_accordion: true
markdown: redcarpet
print: true
theme_file: theme-green.css
# only use suffix if you need to force index.html to display
# suffix: index.html

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

prose:
  media: 'images'
